drawer:
    caption:
    menu:
        主页:
            href: /
            icon: home
        关于:
            href: /about
            icon: person
        友链:
            href: /friend
            icon: link
        归档:
            preset: archive
        RSS:
            preset: rss
            divider: true
        深色模式:
            preset: dark
        访问统计:
            preset: stats_busuanzi

head:
    favicon: /img/favicon.png
    high_res_favicon: /img/favicon.png
    apple_touch_icon: /img/favicon.png
    keywords:
    structured_data: true
    site_verification:
        google:
        baidu:

footer:
    since:
    text: Hosted by <a href="https://pages.github.com/" target="_blank">Github Pages</a>

uiux:
    slogan: This is a slogan.
    sidebar_image: https://picsum.photos/600/400.webp?blur=10
    sidebar_image_color: '#e16b8c'
    banner_image: https://picsum.photos/1200/500.webp
    banner_image_color: '#e16b8c'
    avatar: https://picsum.photos/200/200.webp
    mdui_primary_theme: pink
    mdui_accent_theme: pink
    post_thumbnail_color: '#03a9f4'
    copy_code_button_color: '#fff'
    top:
        enable: true
        style: fab
        # style: akarin

posts:
    default_excerpt: 120
    license: 本作品采用<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

links:
    default_avatar: /img/Transparent_Akkarin.png
    description:
    list:
        Github:
            link: https://github.com/
            avatar: https://github.githubassets.com/images/modules/open_graph/github-logo.png
            description: 全球最大同性交友网站

comment:
    livere:
        enable: false
        uid:

stats:
    busuanzi:
        enable: false
        script: https://cdn.jsdelivr.net/gh/TransparentLC/hexo-theme-akarin/source/js/bsz.min.js
        site_uv: true
        site_pv: true
        page_pv: true

mathjax:

rss:

stylesheets:
- /css/mdui.min.css
- /css/prism-line-numbers.min.css
- /css/prism-vsc-dark-plus.min.css
- /css/style.css

scripts:
- /js/mdui.min.js
- /js/medium-zoom.min.js
- /js/script.js
